# Enables/disables bold
bold=$'%{\e[1m%}'
nobold=$'%{\e[22m%}'

# Resets all styles
reset=$'%{\e[0m%}'

# n = \n
n=$'\n'

# hc = Host color
# sc = Separator color
# dc = Dir color
# pc = Prompt color
hc=$'%{$fg[red]%}'
sc=$'%{$fg_bold[white]%}'
dc=$'%{$fg[yellow]%}'
pc=$'%{$fg[red]%}'

l2="$pc> $reset"

l1_start="$bold$hc%n$sc:$dc%~"
l1_end="$sc%(?.. [$pc%?$sc])"

export PROMPT="$n$l1_start $l1_end$n$l2"

